export const actionTypes = {
	USER_END_INITIALIZATION: 'USER_END_INITIALIZATION',
	USER_START_LOADING: 'USER_START_LOADING',
	USER_STOP_LOADING: 'USER_STOP_LOADING',
	USER_LOGIN: 'USER_LOGIN',
	USER_LOGOUT: 'USER_LOGOUT',
	USER_OTP_SENT: 'USER_OTP_SENT',
	CANCEL_OTP_VERIFICATION: 'CANCEL_OTP_VERIFICATION',
	USER_DETAILS: 'USER_DETAILS',

	UI_END_INITIALIZATION: 'UI_END_INITIALIZATION',

	DATES_START_LOADING: 'DATES_START_LOADING',
	DATES_STOP_LOADING: 'DATES_STOP_LOADING',
	DATES_DATA: 'DATES_DATA',
	DATES_CHANGE: 'DATES_CHANGE',
}
